server:
  port: 84
spring:
  application:
    name: cloud-consumer-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080