server:
  port: 80
spring:
  application:
    name: cloud-consumer-hystrix-80
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 9000
        read-timeout: 9000
  httpclient:
    ok-http:
      read-timeout: 9000
    connection-timeout: 9000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000