server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix8001
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  mvc:
    hiddenmethod:
      filter:
        enabled: true
eureka:
  instance:
    hostname: localhost
    instance-id: cloud-provider-hystrix8001
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
